extends:
 - ./lint/eslintrc-gjs.yml
 - ./lint/eslintrc-shell.yml

overrides:
  - files: ./*.js
    globals:
      global: readonly

# Conform to https://gitlab.gnome.org/GNOME/gjs/-/raw/gnome-3-34/.eslintrc.yml
parserOptions:
  ecmaVersion: 2019
